require("settings")
require("lazyspec")

spec("plugins.colorscheme")
spec("plugins.statusline")
spec("plugins.telescope")
spec("plugins.filetree")
spec("plugins.autoclose")
spec("plugins.treesitter")
spec("plugins.ts-autotag")
spec("plugins.lsp-zero")
spec("plugins.mason")
spec("plugins.autocomplete")
spec("plugins.lspconfig")
spec("plugins.lsp-signature")
spec("plugins.autosearch")
spec("plugins.surround")
spec("plugins.whichkey")
spec("plugins.sessions")

require("plugins.lazy")
require("mappings")

